import Nav from '@/app/[lang]/components/Nav';
import '../globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Kreastol App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="flex flex-col h-screen mx-3">
            <Nav/>
            <main className="w-full h-full">
                {children}
            </main>
        </div>

        </body>
        </html>
    )
}
